### ISSUE TITLE
Stats bugs and improvements

### ISSUE THREAD

**Issue by ahuston-0** [StevensDeptECE/GrailGUI#29]
Currently Stats1D has a .cc file that is not used for much of anything and may not even be part of the compile process. This can likely be removed. Also, apparently a vector of Stats1D objects can cause undefined behavior and crash with a seg fault. This should be investigated to determine who is mismanaging memory (user or Stats1D) and what should be done if this is an internal issue with the Stats1D object.

**Comment by dkrautha** [comment]
@ahuston-0 
It seems like both of these issues have been corrected at this point, the useless `.cc` file is gone, and I haven't been able to replicate the undefined behavior / segfault from working on #47. The reason for the behavior was likely due to the use of pointers/unique pointers previously, which we don't do anymore.

If you think this issue should stay, let me know. If not, I'll leave it to you to close this one.

**Comment by ahuston-0** [comment]
> @ahuston-0
> It seems like both of these issues have been corrected at this point, the useless `.cc` file is gone, and I haven't been able to replicate the undefined behavior / segfault from working on #47. The reason for the behavior was likely due to the use of pointers/unique pointers previously, which we don't do anymore.
> 
> If you think this issue should stay, let me know. If not, I'll leave it to you to close this one.

I had considered closing this last week, but had never gotten around to testing the how a container full of multiple Stats1D's was working. Is that ready to go? I don't necessarily know if we'll ever need to do it, but I'd like to make sure that behavior that we've tested in the past will work going forward. Otherwise, this issue is ready to be closed.

**Comment by dkrautha** [comment]
I wrote a test [here](https://github.com/StevensDeptECE/GrailGUI/blob/env_var_purge/test/testStats.cc) on line 64 that attempts to replicate the original undefined behavior we saw when working with a container of stats objects. It has yet to do any segfaulting on me, so I'm going to call this issue solved and close it.
